name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  GradeTests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile GradeTests
      run: javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar Tests/GradeTests.java

    - name: Run GradeTests
      run: java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore Tests.GradeTests

  SubjectDataTests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile SubjectDataTests
      run: javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar Tests/SubjectDataTests.java

    - name: Run SubjectDataTests
      run: java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore Tests.SubjectDataTests

  marks_to_grade_StatementWhiteBoxTesting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile marks_to_grade_StatementWhiteBoxTesting
      run: javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar Tests/marks_to_grade_StatementWhiteBoxTesting.java

    - name: Run marks_to_grade_StatementWhiteBoxTesting
      run: java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore Tests.marks_to_grade_StatementWhiteBoxTesting

  WhiteBoxTestingPathCoverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile WhiteBoxTestingPathCoverage
      run: javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar Tests/WhiteBoxTestingPathCoverage.java

    - name: Run WhiteBoxTestingPathCoverage
      run: java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore Tests.WhiteBoxTestingPathCoverage

  BlackBoxTesting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile BlackBoxTesting
      run: javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar Tests/BlackBoxTesting.java

    - name: Run BlackBoxTesting
      run: java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore Tests.BlackBoxTesting
  
  calculate_grade_CFG:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile calculate_grade_CFG
      run: javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar Tests/calculate_grade_CFG.java

    - name: Run calculate_grade_CFG
      run: java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore Tests.calculate_grade_CFG

  validate_subject_data_BranchWhiteBox:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile validate_subject_data_BranchWhiteBox
      run: javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar Tests/validate_subject_data_BranchWhiteBox.java

    - name: Run validate_subject_data_BranchWhiteBox
      run: java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore Tests.validate_subject_data_BranchWhiteBox

  WhiteBoxTestingGradeStatmentCoverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Compile WhiteBoxTestingGradeStatmentCoverage
      run: javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar Tests/WhiteBoxTestingGradeStatmentCoverage.java

    - name: Run WhiteBoxTestingGradeStatmentCoverage
      run: java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore Tests.WhiteBoxTestingGradeStatmentCoverage